"""empty message

Revision ID: 44d5a1bdf868
Revises: a9edf5f85259
Create Date: 2020-09-16 19:20:39.860592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44d5a1bdf868'
down_revision = 'a9edf5f85259'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('reciever', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'reciever')
    # ### end Alembic commands ###
