"""empty message

Revision ID: 4aecd0667aa9
Revises: 4598bd7e52be
Create Date: 2020-09-14 04:56:58.861386

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4aecd0667aa9'
down_revision = '4598bd7e52be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogpost', sa.Column('date', sa.DateTime(), nullable=True))
    op.drop_column('blogpost', 'date_posted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogpost', sa.Column('date_posted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('blogpost', 'date')
    # ### end Alembic commands ###
