"""empty message

Revision ID: 645250a0928f
Revises: c3c0dd8f5d6d
Create Date: 2020-09-12 03:00:32.266497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '645250a0928f'
down_revision = 'c3c0dd8f5d6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogpost', sa.Column('access', sa.Boolean(), nullable=True))
    op.add_column('blogpost', sa.Column('imagelink', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogpost', 'imagelink')
    op.drop_column('blogpost', 'access')
    # ### end Alembic commands ###
