"""empty message

Revision ID: f4ecd2a606e4
Revises: 645250a0928f
Create Date: 2020-09-12 03:03:06.032187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4ecd2a606e4'
down_revision = '645250a0928f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blogpost', 'access',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('blogpost', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blogpost', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('blogpost', 'access',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
